### PR TITLE
Submit a Simplified Chinese translation file for README

### PR DESCRIPTION
**Pull request by Zhoneym**
Submit a Simplified Chinese translation file for README

### CODE REVIEW

**Comment by BenTheElder** [comment]
Hmm, without an active program to manage this, it seems it will just fall out of sync with our existing docs.

Reaching out to SIG docs who do maintain translations for kubernetes/website.

**Comment by sftim** [comment]
/hold

We don't have reviewers and approvers who can review and maintain this document; nor do we plan to.

OK to unhold if we do have a team of SIG Release approvers who can maintain Chinese and would like this README to exist with localized content.

**Comment by reylejano** [comment]
I agree with @sftim that SIG Docs does not have reviewers and approvers to maintain this and is outside the scope of the zn localization team 

@Zhoneym , you can contact the SIG Docs zh localization team on the [#documentation-docs-zh on Kubernetes Slack](https://kubernetes.slack.com/archives/CE3LNFYJ1)

I'm ok to close this PR unless SIG Release would like the README localized and has reviewers/approvers to maintain

**Comment by mrbobbytables** [comment]
One other potential thought,  would it be worth adding a page somewhere on k8s.io about registry.k8s.io,  the stability guarantees and basic troubleshooting? That would keep it in a place where localization drift could be tracked.

**Comment by sftim** [comment]
> One other potential thought, would it be worth adding a page somewhere on k8s.io about registry.k8s.io, the stability guarantees and basic troubleshooting? That would keep it in a place where localization drift could be tracked.

Yes, that _is_ a good idea. The (English) README can link there, too.

Might end up being two pages as troubleshooting docs are separated out.

**Comment by BenTheElder** [comment]
Let's plan to do that instead. Thank you all!

**Pull request closed without merging**
