### PR TITLE
chore: update go version in .go-version

### PR DESCRIPTION
**Pull request by Okabe-Junya**
## Change List

- update go version (like #267)

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
/assign bentheelder
for approval (as the author of 267)

**Comment by Okabe-Junya** [comment]
/retitle chore: update go version in .go-version

**Review by TerryHowe — COMMENTED** [review]
/lgtm

**Review by TerryHowe — APPROVED** [review]

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
